In [11]:
import pandas as pd
import pyodbc
from warnings import filterwarnings

In [12]:
# import pandas as pd

# # 1. Create a list of your 5 CSV file paths
# files = ['../begin_inventory.csv', '../purchase_prices.csv', '../purchases.csv', '../sales.csv', '../end_inventory.csv']

# # 2. Use a for loop to read each and print the row count
# for file in files:
#     data = pd.read_csv(file)
#     print(f"{file}\n")
#     print(data.head(5))

In [13]:
# df= pd.read_csv('../sales.csv')
# df.info()

In [14]:
conn = pyodbc.connect('DRIVER={SQL Server};SERVER=LAPTOP-JF5CSB68\SQLEXPRESS;DATABASE=My_Project;Trusted_Connection=yes;')
if conn:
    print("Connection successful!")

Connection successful!

<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7268\1838932837.py:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  conn = pyodbc.connect('DRIVER={SQL Server};SERVER=LAPTOP-JF5CSB68\SQLEXPRESS;DATABASE=My_Project;Trusted_Connection=yes;')

In [15]:
purchases = pd.read_sql_query('SELECT * FROM purchases where VendorNumber = 4466', conn)
purchases

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7268\76446512.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  purchases = pd.read_sql_query('SELECT * FROM purchases where VendorNumber = 4466', conn)

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.400002,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.049999,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.099998,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.459999,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.459999,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.459999,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.750000,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.049999,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.459999,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.750000,1

In [16]:
purchase_price = pd.read_sql_query('SELECT * FROM purchase_prices where VendorNumber = 4466', conn)
purchase_price

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7268\2685471258.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  purchase_price = pd.read_sql_query('SELECT * FROM purchase_prices where VendorNumber = 4466', conn)

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

vendor_invoice = pd.read_sql_query('SELECT * FROM vendor_invoice where VendorNumber = 4466', conn)
vendor_invoice

In [17]:
sales = pd.read_sql_query("select * from sales where VendorNo = 4466", conn)
sales

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7268\1173318207.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sales = pd.read_sql_query("select * from sales where VendorNo = 4466", conn)

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [18]:
purchases.groupby(['Brand', 'PurchasePrice'])[['Quantity', 'Dollars']].sum()

                     Quantity       Dollars
Brand PurchasePrice
3140  11.19              4640  51921.599669
5215  9.41               4923  46325.429382
5255  9.35               6215  58110.248949

In [27]:
# purchase_price
vendor_invoice = pd.read_sql_query("select * from vendor_invoice", conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7268\285574814.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vendor_invoice = pd.read_sql_query("select * from vendor_invoice", conn)

In [28]:
vendor_invoice['PONumber'].nunique()

5543

In [29]:
vendor_invoice.shape

(5543, 10)

In [30]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [21]:
sales.groupby('Brand')[["SalesDollars", "SalesPrice", "SalesQuantity"]].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       50531.10    30071.85           3890
5215       60416.49    41542.02           4651
5255       79187.04    51180.60           6096

### Calculating freight cost fro each vendors using sql query

In [22]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [23]:
freight_summary = pd.read_sql_query("select VendorNumber, SUM(Freight) as FreightCost from vendor_invoice group by VendorNumber order by VendorNumber asc", conn)
freight_summary

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7268\401002919.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  freight_summary = pd.read_sql_query("select VendorNumber, SUM(Freight) as FreightCost from vendor_invoice group by VendorNumber order by VendorNumber asc", conn)

     VendorNumber  FreightCost
0               2    27.080001
1              54     0.480000
2              60   367.520002
3             105    62.389999
4             200     6.190000
..            ...          ...
121         98450   856.019997
122         99166   130.090001
123        172662   178.340000
124        173357   202.500001
125        201359     0.090000

[126 rows x 2 columns]

In [24]:
pd.read_sql_query( """
SELECT 
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,           
    pp.Volume,                 
    pp.Price AS ActualPrice,   
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp ON p.Brand = pp.Brand
WHERE p.PurchasePrice > 0
GROUP BY 
    p.VendorNumber, 
    p.VendorName, 
    p.Brand, 
    p.PurchasePrice,     
    pp.Volume,                 
    pp.Price                   
ORDER BY TotalPurchaseDollars;
""", conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7268\148718205.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query( """

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.710000,50.0,0.990000,1,7.100000e-01
1,3960,DIAGEO NORTH AMERICA INC,6127,1.470000,200.0,1.990000,1,1.470000e+00
2,3924,HEAVEN HILL DISTILLERIES,9123,0.740000,50.0,0.990000,2,1.480000e+00
3,8004,SAZERAC CO INC,5683,0.390000,50.0,0.490000,6,2.340000e+00
4,9815,WINE GROUP INC,8527,1.320000,750.0,4.990000,2,2.640000e+00
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.889999,1750.0,29.990000,138109,3.023206e+06
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.170000,1750.0,22.990000,201682,3.261198e+06
10689,17035,PERNOD RICARD USA,8068,18.240000,1750.0,24.990000,187407,3.418304e+06
10690,4425,MARTIGNETTI COMPANIES,3405,23.190001,1750.0,28.990000,164038,3.804041e+06
10691,1128,BROWN-FORMAN CORP,1233,26.270000,1750.0,36.990002,145080,3.811252e+06

In [34]:
pd.read_sql_query("""SELECT
                  VendorNo,
                  Brand,
                  SUM(SalesDollars) AS TotalSalesDollars,
                  SUM(SalesPrice) AS TotalSalesPrice,
                  SUM(SalesQuantity) AS TotalSalesQuantity,
                  SUM(ExciseTax) AS TotalExciseTax
                  FROM sales
                  Group By VendorNo,Brand
                  Order by TotalSalesDollars
                  """,conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7268\904892026.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("""SELECT

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,9206,2773,0.99,0.99,1,0.05
2,3252,3933,1.98,0.99,2,0.10
3,10050,3623,1.98,1.98,2,0.10
4,3924,9123,1.98,0.99,2,0.10
...,...,...,...,...,...,...
11267,3960,3545,4223107.62,545778.28,135838,249587.83
11268,3960,4261,4475972.88,420050.01,200412,368242.80
11269,17035,8068,4538120.60,461140.15,187140,343854.07
11270,4425,3405,4819073.49,561512.37,160247,294438.66
11271,1128,1233,5101919.51,672819.31,142049,260999.20

In [ ]:
# import time 
# start = time.time()
# final_table = pd.read_sql_query("""SELECT 
#                                 pp.VendorNumber,
#                                 pp.Brand,
#                                 pp.Price AS ActualPrice,
#                                 pp.PurchasePrice,
#                                 SUM(s.SalesDollars) AS TotalSalesDollars,
#                                 SUM(s.SalesPrice) AS TotalSalesPrice,
#                                 SUM(SalesQuantity) AS TotalSalesQuantity,
#                                 SUM(ExciseTax) AS TotalExciseTax,
#                                 SUM(vi.Quantity) AS TotalPurchaseQuantity,
#                                 SUM(vi.Dollars) AS TotalPurchaseDollars,
#                                 SUM(vi.Freight) AS TotalFreightCost
#                                 from purchase_prices pp
#                                 JOIN sales s
#                                 ON pp.VendorNumber = s.VendorNo
#                                 AND pp.Brand = s.Brand 
#                                 JOIN vendor_invoice vi
#                                 ON pp.VendorNumber = vi.VendorNumber
#                                 GROUP BY pp.VendorNumber, pp.Brand, pp.Price, pp.PurchasePrice
#                                 """,conn)
# end = time.time()